name: CMD-ONTE
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::minimap2=2.17
    - bioconda::sniffles=1.0.11
    - bioconda::samtools
    - bioconda::sambamba
    - bioconda::mosdepth
    - bioconda::nanoplot
    - bioconda::npinv
    - bioconda::svim